services:
  # Service PHP avec Apache
  php:
    build:
      context: ./php
    container_name: symfony_php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:azerty@database:3306/mabase?serverVersion=8.0
      - REDIS_URL=redis://redis:6379
      - MAILER_DSN=smtp://mailer:1025
    depends_on:
      - database
      - redis

  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: symfony_database
    environment:
      MYSQL_DATABASE: mabase
      MYSQL_USER: symfony
      MYSQL_PASSWORD: azerty
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: symfony_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  # Service mail pour le développement
  mailer:
    image: axllent/mailpit
    container_name: symfony_mailer
    ports:
      - "8025:8025"  # Interface web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # phpMyAdmin pour gérer MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: azerty
      MYSQL_ROOT_PASSWORD: "rootpassword"
    depends_on:
      - database
